version: '3'
services:
  mysql:
    image: mysql:5.7.25

    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test

  redis:
    image: redis:4.0.10
    container_name: redis
    ports:
      - "6379:6379"

  redisCommander:
    container_name: redis-commander-container
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
      TZ: "Asia/Tokyo"
    ports:
    - "8081:8081"
    depends_on:
    - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      #PMA_ARBITRARY: 1
      #PMA_HOST: host.docker.internal
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    restart: always
    ports:
    - "18080:80"
    volumes:
    - /sessions
